Project/social/posts/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.posts_list, name='posts_list'),
    path('create/', views.posts_create, name='posts_create'),
    path('<int:post_id>/edit/', views.posts_edit, name='posts_edit'),
    path('<int:post_id>/delete/', views.posts_delete, name='posts_delete'),
    path('register/', views.register, name='register'),
    path('search/', views.search, name='search'),
] 

Project/social/social/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.urls import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/social/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Posts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=240)
    photo = models.ImageField(upload_to='photos/',blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.username}- {self.text[:10]}'

Project/social/posts/forms.py
from django import forms
from .models import Posts
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class PostsForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ['text', 'photo']

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

Project/social/posts/views.py
from django.shortcuts import render, HttpResponse
from .models import Posts
from .forms import PostsForm, UserRegistrationForm
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from posts.models import Posts

# Create your views here.

def index(request):
    return render(request, 'index.html')


def posts_list(request):
    posts = Posts.objects.all().order_by('-created_at')
    return render(request, 'index.html',{'posts':posts})


@login_required
def posts_create(request):
    if request.method == "POST":
        form = PostsForm(request.POST, request.FILES)
        if form.is_valid():
            posts = form.save(commit=False)
            posts.user = request.user
            posts.save()
            return redirect('posts_list')
        
    else:
        form = PostsForm()
    return render(request, 'posts_form.html', {'form':form})


@login_required
def posts_edit(request, post_id):
    posts = get_object_or_404(Posts, pk=post_id, user = request.user)
    if request.method == 'POST':
        form = PostsForm(request.POST, request.FILES, instance=posts)
        if form.is_valid():
            posts = form.save(commit=False)
            posts.user = request.user
            posts.save()
            return redirect('posts_list')
    else:
        form = PostsForm(instance=posts)
    return render(request, 'posts_form.html', {'form':form})


@login_required
def posts_delete(request, post_id):
    posts = get_object_or_404(Posts, pk=post_id, user = request.user)
    if request.method == 'POST':
        posts.delete()
        return redirect('posts_list')
    return render(request, 'posts_confirm_delete.html', {'posts':posts})

    
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            login(request, user)
            return redirect(posts_list)

    else:
        form = UserRegistrationForm()


    return render(request, 'registration/register.html', {'form':form})


def search(request):
    allPosts = Posts.objects.all()
    params = {'allPosts': allPosts}
    return render(request, 'search.html', params)
    # return HttpResponse('This is search')

Project/social/social/views.py
from django.http import HttpResponse
from django.shortcuts import render



Project/social/posts/templates/index.html
{% extends "layout.html" %}

{% block title %}
Posts
{% endblock %}

{% block content %}
<h1 class="text-center mt-4">Welcome to Posts Page</h1>

<a class="btn btn-primary mb-4" href="{% url 'posts_create' %}">Create a Post</a>
<div class="container row gap-3">
    {% for post in posts %}
    <div class="card" style="width: 20rem; background-color: rgba(127, 130, 187, 0.5);">
        <img src="{{post.photo.url}}" class="card-img-top mt-3" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{post.user.username}}</h5>
          <p class="card-text">{{post.text}}</p>
          {% if post.user == user %}
          <a href="{% url 'posts_edit' post.id%}" class="btn btn-primary">Edit</a>
          <a href="{% url 'posts_delete' post.id%}" class="btn btn-danger">Delete</a>
          {% endif %}
        </div>
      </div>
      {% endfor %}
</div>


{% endblock %}

Project/social/posts/templates/posts_confirm_delete.html
{% extends "layout.html" %}

{% block title %}
Posts
{% endblock %}

{% block content %}
<h1 class="text-center mt-4">Are you sure that you want to delete this post</h1>

<form  method="post">
    {% csrf_token %}
    <button class="btn btn-danger">Delete</button>
    <a class="btn btn-success" href="{% url 'posts_list' %}">Cancel</a>
</form>

{% endblock %}

Project/social/posts/templates/posts_form.html
{% extends "layout.html" %}

{% block title %}
Create Post
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-center">
                    <h2>Create a New Post</h2>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                            <label for="id_photo">Upload Photo</label>
                            <input type="file" name="photo" id="id_photo" class="form-control-file">
                        </div>
                        <div class="form-group mb-3">
                            <label for="id_text">Post Text</label>
                            <textarea name="text" id="id_text" class="form-control" rows="4" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Create Post</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Project/social/posts/templates/search.html
{% extends "layout.html" %}

{% block title %}
Search results
{% endblock %}

{% block content %}
<h1 class="text-center mt-4">Search results</h1>

<a class="btn btn-primary mb-4" href="{% url 'posts_create' %}">Create a Post</a>
<div class="container row gap-3">
    {% for post in posts %}
    <div class="card" style="width: 20rem; background-color: rgba(127, 130, 187, 0.5);">
        <img src="{{post.photo.url}}" class="card-img-top mt-3" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{post.user.username}}</h5>
          <p class="card-text">{{post.text}}</p>
          {% if post.user == user %}
          <a href="{% url 'posts_edit' post.id%}" class="btn btn-primary">Edit</a>
          <a href="{% url 'posts_delete' post.id%}" class="btn btn-danger">Delete</a>
          {% endif %}
        </div>
      </div>
      {% endfor %}
</div>


{% endblock %}

Project/social/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
  
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>
        {% block title %}
        Social
        {% endblock %}
    </title>
</head>
<body><nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Social</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'posts_list' %}" >Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.instagram.com/_ashish.2822/">Link</a>
          </li>
          {% comment %} <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
          </li> {% endcomment %}
        </ul>
        <form method="get" action="{% url 'search' %}" class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query" id="query">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        {% if user.is_authenticated %}
        <form  method="post" action="{% url 'logout' %}">
          {% csrf_token %}
          <button class="btn btn-danger mx-2" type="submit">Logout</button>
        </form>
        {% else %}
        <a href="{% url 'register' %}" class="btn btn-primary mx-2">Register</a>
        <a href="{% url 'login' %}" class="btn btn-success mx-2">Login</a>
        {% endif %}
        
      </div>
    </div>
  </nav>
  
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>